### ISSUE TITLE
Controller with constructor argument is not supperted

### ISSUE THREAD

**Issue by atul221282** [apazureck/openui5vscodeTypescriptTools#47]
Currently cannot see how we can use this to create controller class with some constructor arguments

**Comment by apazureck** [comment]
Hi @atul221282,

That depends on what typings you are using. And you will have to use some "hacky" adding of methods to the generated ui5 class, as the inheritance system is completely different to the ES version.

The extension is sadly a little bit on hold the last time. I was writing a parser for ui5ts and the extension will go that direction. This will also spare you the pain to add the generated code manually to your UI5 extended class. Maybe you should check out that npm package.

This extension is more about productivity in UI5 using Typescript to get the work done.

Let me know if you need some more information.

Regards

**Comment by atul221282** [comment]
Thanks for your prompt reply and well-defined explanation. I am working on an enterprise application and really don't want to use some other npm package where I am not sure about the support.

**Comment by apazureck** [comment]
@atul221282:

I don't think you will go wrong with ui5ts, I am using ts since 2 years with UI5 and it is by far the best approach to that topic getting plain es6 syntax.

But you will have to get pretty much knowledge about typescript yourself for now to be on the safe side.

regards
